### ISSUE TITLE
Push version 0.3.0 to Hackage

### ISSUE THREAD

**Issue by sumo** [tvh/hasql-migration#10]
Are you able to push the latest version to hackage?

**Comment by theobat** [comment]
I'd be interested as well...

**Comment by theobat** [comment]
@tvh I can offer help for maintaining the project if you cannot/don't want to maintain it anymore (If you're open to the idea of course). I'm using it professionally so I already maintain a fork...

**Comment by tvh** [comment]
I just pushed 0.3.0 to Hackage.

@theobat Thanks for the offer! I just invited you as a collaborator on the repo. I don't use this package myself currently.

**Comment by theobat** [comment]
All right thanks !
